initUrl: "jdbc:mysql://127.0.0.1:4000?serverTimezone=UTC&useServerPrepStmts=true&cachePrepStmts=true"
connUrl: "jdbc:mysql://127.0.0.1:4000/reproduceDB?serverTimezone=UTC&useServerPrepStmts=true&cachePrepStmts=true"
database: "reproduceDB"
user: "root"
password: ""
initList:
  - "create table table_7_2(a int primary key, b int, c double);"
  - "insert into table_7_2 values(676, 5012153, 2240641.4);"
operationList:
  - trxId: "1001"
    sql: "select * from table_7_2;"
  - trxId: "1001"
    sql: "commit;"
  - trxId: "739"
    sql: "update table_7_2 set b=5012153 and c=2240641.4 where a=676;"
  - trxId: "739"
    sql: "commit;"
  - trxId: "1000"
    sql: "select * from table_7_2;"
  - trxId: "1000"
    sql: "commit;"