# TiDB Version: 3.0.5
# 
# Description:
# In the table above, for the record(3873) of table_ 8_2, 
# there are two historical versions of attribute6, 
# the first is -0.386, the creation time is (105092144188546105092148615512); 
# the second is 0.484, the creation time is (10509218265039105092186223727). 
# The start timestamp of transaction 914 is in the interval (1050921876735105092191263618), 
# then the attribute6 of transaction 914 reading record 3873 should be 0.484, 
# but TiDB returns -0.386, indicating that there is a problem with the consistency reading of TiDB.

initUrl: "jdbc:mysql://127.0.0.1:4000?serverTimezone=UTC&useServerPrepStmts=true&cachePrepStmts=true"
connUrl: "jdbc:mysql://127.0.0.1:4000/reproduceDB?serverTimezone=UTC&useServerPrepStmts=true&cachePrepStmts=true"
database: "reproduceDB"
user: "root"
password: ""
initList:
  - "create table table_8_2(primarykey int primary key, attribute1 double, attribute6 double);"
  - "insert into table_8_2 values(3873, 0.213, 0.234);"
operationList:
  - trxId: "1"
    sql: "update table_8_2 set attribute6=-0.386 where primarykey=3873;"
  - trxId: "1"
    sql: "commit;"
  - trxId: "2"
    sql: "SET TRANSACTION ISOLATION LEVEL Repeatable Read;"
  - trxId: "3"
    sql: "update table_8_2 set attribute6=0.484 where primarykey=3873;"
  - trxId: "3"
    sql: "commit;"
  - trxId: "2"
    sql: "select attribute1 from table_8_2 where primarykey=3873;"
  - trxId: "2"
    sql: "select attribute6 from table_8_2 where primarykey=3873;"
